name: Test

on:
  push:
    branches:
    - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  schedule:
    - cron: "0 0 * * 5"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf plugin test
        uses: asdf-vm/actions/plugin-test@v1.1.0
        with:
          command: svu --version